database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: mdhawan

  # the password
  password: 1234

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/mdhawan
  validationQuery: "SELECT * FROM INFORMATION_SCHEMA.TABLES"
  maxWaitForConnection: 30s

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: validate
    show_sql: true
    hibernate.show_sql: true
    hibernate.format_sql: true
    format_sql: true
    use_sql_comments: true
    hibernate.use_sql_comments: true
    h2.tcpAllowOthers: true
